### ISSUE TITLE
width problem in css section about me

### ISSUE THREAD

**Issue by othmane-boudiab** [othmane-boudiab/portfolio#3]
line 123
```css
.presentation {
    width: 100%;
}
```
```css
.presentation {
    width: calc(100% - 300px);
    margin-left: auto;
}
```
